# Generated by Django 4.0.5 on 2022-06-26 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('corporate_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issuance', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('date_due', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('date_anticipation', models.DateField(blank=True, null=True, verbose_name='Data de Antecipação')),
                ('value_original', models.FloatField(blank=True, null=True, verbose_name='Valor Original')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Valor Desconto')),
                ('value_with_discount', models.FloatField(blank=True, null=True, verbose_name='Valor com Desconto')),
                ('status', models.CharField(blank=True, choices=[('DISPO', 'Disponível'), ('INDIS', 'Indisponível'), ('AGUAR', 'Aguardando Confirmação'), ('ACEIT', 'Aceito'), ('NEGAD', 'Negado')], max_length=50, null=True, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.provider')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
            },
        ),
    ]
