# Generated by Django 4.0.5 on 2022-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_provider_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('DISPO', 'Disponível'), ('INDIS', 'Indisponível'), ('AGUAR', 'Aguardando Confirmação'), ('APROV', 'Aprovado'), ('NEGAD', 'Negado')], max_length=50, null=True, verbose_name='Situação'),
        ),
    ]
